# -*- coding: utf-8 -*-
"""历史年号候选库：带主题字与吉凶向，供语义主题链选号。"""

NIANHAO_ENTRIES = [
    {'name': '建元', 'themes': ['建', '元'], 'tone': 'auspicious', 'weight': 12},
    {'name': '元光', 'themes': ['元', '光'], 'tone': 'auspicious', 'weight': 12},
    {'name': '元朔', 'themes': ['元'], 'tone': 'auspicious', 'weight': 12},
    {'name': '元狩', 'themes': ['元'], 'tone': 'auspicious', 'weight': 12},
    {'name': '元鼎', 'themes': ['元'], 'tone': 'auspicious', 'weight': 12},
    {'name': '元封', 'themes': ['元'], 'tone': 'auspicious', 'weight': 12},
    {'name': '太初', 'themes': ['太'], 'tone': 'auspicious', 'weight': 12},
    {'name': '天汉', 'themes': ['天'], 'tone': 'auspicious', 'weight': 12},
    {'name': '太始', 'themes': ['太'], 'tone': 'neutral', 'weight': 10},
    {'name': '征和', 'themes': ['征', '和'], 'tone': 'mitigate', 'weight': 11},
    {'name': '后元', 'themes': ['后', '元'], 'tone': 'auspicious', 'weight': 12},
    {'name': '始元', 'themes': ['始', '元'], 'tone': 'auspicious', 'weight': 12},
    {'name': '元凤', 'themes': ['元', '凤'], 'tone': 'auspicious', 'weight': 12},
    {'name': '本始', 'themes': ['本'], 'tone': 'neutral', 'weight': 10},
    {'name': '地节', 'themes': ['地'], 'tone': 'neutral', 'weight': 10},
    {'name': '元康', 'themes': ['元', '康'], 'tone': 'auspicious', 'weight': 12},
    {'name': '神爵', 'themes': ['神'], 'tone': 'neutral', 'weight': 10},
    {'name': '五凤', 'themes': ['五', '凤'], 'tone': 'auspicious', 'weight': 12},
    {'name': '甘露', 'themes': ['甘'], 'tone': 'neutral', 'weight': 10},
    {'name': '黄龙', 'themes': ['黄', '龙'], 'tone': 'auspicious', 'weight': 12},
    {'name': '初元', 'themes': ['初', '元'], 'tone': 'auspicious', 'weight': 12},
    {'name': '永光', 'themes': ['永', '光'], 'tone': 'neutral', 'weight': 10},
    {'name': '建昭', 'themes': ['建'], 'tone': 'neutral', 'weight': 10},
    {'name': '竟宁', 'themes': ['竟', '宁'], 'tone': 'mitigate', 'weight': 11},
    {'name': '建始', 'themes': ['建'], 'tone': 'neutral', 'weight': 10},
    {'name': '河平', 'themes': ['河', '平'], 'tone': 'mitigate', 'weight': 11},
    {'name': '阳朔', 'themes': ['阳'], 'tone': 'neutral', 'weight': 10},
    {'name': '鸿嘉', 'themes': ['鸿', '嘉'], 'tone': 'neutral', 'weight': 10},
    {'name': '永始', 'themes': ['永'], 'tone': 'neutral', 'weight': 10},
    {'name': '元延', 'themes': ['元', '延'], 'tone': 'auspicious', 'weight': 12},
    {'name': '绥和', 'themes': ['绥', '和'], 'tone': 'mitigate', 'weight': 11},
    {'name': '建平', 'themes': ['建', '平'], 'tone': 'mitigate', 'weight': 11},
    {'name': '元寿', 'themes': ['元', '寿'], 'tone': 'auspicious', 'weight': 12},
    {'name': '元始', 'themes': ['元'], 'tone': 'auspicious', 'weight': 12},
    {'name': '居摄', 'themes': ['居'], 'tone': 'neutral', 'weight': 10},
    {'name': '初始', 'themes': ['初'], 'tone': 'neutral', 'weight': 10},
    {'name': '建国', 'themes': ['建'], 'tone': 'neutral', 'weight': 10},
    {'name': '天凤', 'themes': ['天', '凤'], 'tone': 'auspicious', 'weight': 12},
    {'name': '地皇', 'themes': ['地', '皇'], 'tone': 'neutral', 'weight': 10},
    {'name': '更始', 'themes': ['更'], 'tone': 'mitigate', 'weight': 11},
    {'name': '建武', 'themes': ['建', '武'], 'tone': 'auspicious', 'weight': 12},
    {'name': '永平', 'themes': ['永', '平'], 'tone': 'auspicious', 'weight': 12},
    {'name': '建初', 'themes': ['建'], 'tone': 'neutral', 'weight': 10},
    {'name': '元和', 'themes': ['元', '和'], 'tone': 'auspicious', 'weight': 12},
    {'name': '章和', 'themes': ['章', '和'], 'tone': 'mitigate', 'weight': 11},
    {'name': '永元', 'themes': ['永', '元'], 'tone': 'auspicious', 'weight': 12},
    {'name': '元兴', 'themes': ['元', '兴'], 'tone': 'auspicious', 'weight': 12},
    {'name': '延平', 'themes': ['延', '平'], 'tone': 'mitigate', 'weight': 11},
    {'name': '永初', 'themes': ['永'], 'tone': 'neutral', 'weight': 10},
    {'name': '元初', 'themes': ['元'], 'tone': 'auspicious', 'weight': 12},
    {'name': '永宁', 'themes': ['永', '宁'], 'tone': 'mitigate', 'weight': 11},
    {'name': '建光', 'themes': ['建', '光'], 'tone': 'neutral', 'weight': 10},
    {'name': '延光', 'themes': ['延', '光'], 'tone': 'neutral', 'weight': 10},
    {'name': '永建', 'themes': ['永', '建'], 'tone': 'neutral', 'weight': 10},
    {'name': '阳嘉', 'themes': ['阳', '嘉'], 'tone': 'neutral', 'weight': 10},
    {'name': '永和', 'themes': ['永', '和'], 'tone': 'auspicious', 'weight': 12},
    {'name': '汉安', 'themes': ['汉', '安'], 'tone': 'mitigate', 'weight': 11},
    {'name': '建康', 'themes': ['建', '康'], 'tone': 'mitigate', 'weight': 11},
    {'name': '永嘉', 'themes': ['永', '嘉'], 'tone': 'neutral', 'weight': 10},
    {'name': '本初', 'themes': ['本'], 'tone': 'neutral', 'weight': 10},
    {'name': '建和', 'themes': ['建', '和'], 'tone': 'mitigate', 'weight': 11},
    {'name': '和平', 'themes': ['和', '平'], 'tone': 'mitigate', 'weight': 11},
    {'name': '元嘉', 'themes': ['元', '嘉'], 'tone': 'auspicious', 'weight': 12},
    {'name': '永兴', 'themes': ['永', '兴'], 'tone': 'neutral', 'weight': 10},
    {'name': '永寿', 'themes': ['永', '寿'], 'tone': 'auspicious', 'weight': 12},
    {'name': '延熹', 'themes': ['延'], 'tone': 'neutral', 'weight': 10},
    {'name': '永康', 'themes': ['永', '康'], 'tone': 'mitigate', 'weight': 11},
    {'name': '建宁', 'themes': ['建', '宁'], 'tone': 'mitigate', 'weight': 11},
    {'name': '熹平', 'themes': ['熹', '平'], 'tone': 'mitigate', 'weight': 11},
    {'name': '光和', 'themes': ['光', '和'], 'tone': 'mitigate', 'weight': 11},
    {'name': '中平', 'themes': ['中', '平'], 'tone': 'mitigate', 'weight': 11},
    {'name': '光熹', 'themes': ['光'], 'tone': 'neutral', 'weight': 10},
    {'name': '昭宁', 'themes': ['昭', '宁'], 'tone': 'mitigate', 'weight': 11},
    {'name': '初平', 'themes': ['初', '平'], 'tone': 'mitigate', 'weight': 11},
    {'name': '兴平', 'themes': ['兴', '平'], 'tone': 'mitigate', 'weight': 11},
    {'name': '建安', 'themes': ['建', '安'], 'tone': 'auspicious', 'weight': 12},
    {'name': '延康', 'themes': ['延', '康'], 'tone': 'mitigate', 'weight': 11},
    {'name': '黄初', 'themes': ['黄'], 'tone': 'auspicious', 'weight': 12},
    {'name': '太和', 'themes': ['太', '和'], 'tone': 'auspicious', 'weight': 12},
    {'name': '青龙', 'themes': ['青', '龙'], 'tone': 'auspicious', 'weight': 12},
    {'name': '景初', 'themes': ['景'], 'tone': 'neutral', 'weight': 10},
    {'name': '正始', 'themes': ['正'], 'tone': 'neutral', 'weight': 10},
    {'name': '嘉平', 'themes': ['嘉', '平'], 'tone': 'mitigate', 'weight': 11},
    {'name': '正元', 'themes': ['正', '元'], 'tone': 'auspicious', 'weight': 12},
    {'name': '景元', 'themes': ['景', '元'], 'tone': 'auspicious', 'weight': 12},
    {'name': '咸熙', 'themes': ['咸', '熙'], 'tone': 'neutral', 'weight': 10},
    {'name': '泰始', 'themes': ['泰'], 'tone': 'mitigate', 'weight': 11},
    {'name': '咸宁', 'themes': ['咸', '宁'], 'tone': 'mitigate', 'weight': 11},
    {'name': '太康', 'themes': ['太', '康'], 'tone': 'auspicious', 'weight': 12},
    {'name': '太熙', 'themes': ['太', '熙'], 'tone': 'neutral', 'weight': 10},
    {'name': '永熙', 'themes': ['永', '熙'], 'tone': 'neutral', 'weight': 10},
    {'name': '太安', 'themes': ['太', '安'], 'tone': 'mitigate', 'weight': 11},
    {'name': '永安', 'themes': ['永', '安'], 'tone': 'mitigate', 'weight': 11},
    {'name': '建兴', 'themes': ['建', '兴'], 'tone': 'auspicious', 'weight': 12},
    {'name': '太兴', 'themes': ['太', '兴'], 'tone': 'neutral', 'weight': 10},
    {'name': '永昌', 'themes': ['永'], 'tone': 'neutral', 'weight': 10},
    {'name': '太宁', 'themes': ['太', '宁'], 'tone': 'mitigate', 'weight': 11},
    {'name': '咸和', 'themes': ['咸', '和'], 'tone': 'mitigate', 'weight': 11},
    {'name': '咸康', 'themes': ['咸', '康'], 'tone': 'mitigate', 'weight': 11},
    {'name': '升平', 'themes': ['升', '平'], 'tone': 'mitigate', 'weight': 11},
    {'name': '隆和', 'themes': ['隆', '和'], 'tone': 'mitigate', 'weight': 11},
    {'name': '兴宁', 'themes': ['兴', '宁'], 'tone': 'mitigate', 'weight': 11},
    {'name': '咸安', 'themes': ['咸', '安'], 'tone': 'mitigate', 'weight': 11},
    {'name': '宁康', 'themes': ['宁', '康'], 'tone': 'mitigate', 'weight': 11},
    {'name': '太元', 'themes': ['太', '元'], 'tone': 'auspicious', 'weight': 12},
    {'name': '隆安', 'themes': ['隆', '安'], 'tone': 'mitigate', 'weight': 11},
    {'name': '义熙', 'themes': ['义', '熙'], 'tone': 'neutral', 'weight': 10},
    {'name': '元熙', 'themes': ['元', '熙'], 'tone': 'auspicious', 'weight': 12},
    {'name': '开皇', 'themes': ['开', '皇'], 'tone': 'auspicious', 'weight': 12},
    {'name': '仁寿', 'themes': ['仁', '寿'], 'tone': 'auspicious', 'weight': 12},
    {'name': '大业', 'themes': ['大'], 'tone': 'auspicious', 'weight': 12},
    {'name': '义宁', 'themes': ['义', '宁'], 'tone': 'mitigate', 'weight': 11},
    {'name': '武德', 'themes': ['武'], 'tone': 'auspicious', 'weight': 12},
    {'name': '贞观', 'themes': ['贞'], 'tone': 'auspicious', 'weight': 12},
    {'name': '永徽', 'themes': ['永'], 'tone': 'auspicious', 'weight': 12},
    {'name': '显庆', 'themes': ['显', '庆'], 'tone': 'auspicious', 'weight': 12},
    {'name': '龙朔', 'themes': ['龙'], 'tone': 'auspicious', 'weight': 12},
    {'name': '麟德', 'themes': ['麟'], 'tone': 'auspicious', 'weight': 12},
    {'name': '乾封', 'themes': ['乾'], 'tone': 'neutral', 'weight': 10},
    {'name': '总章', 'themes': ['总'], 'tone': 'neutral', 'weight': 10},
    {'name': '咸亨', 'themes': ['咸'], 'tone': 'neutral', 'weight': 10},
    {'name': '上元', 'themes': ['上', '元'], 'tone': 'auspicious', 'weight': 12},
    {'name': '仪凤', 'themes': ['仪', '凤'], 'tone': 'auspicious', 'weight': 12},
    {'name': '调露', 'themes': ['调'], 'tone': 'neutral', 'weight': 10},
    {'name': '永隆', 'themes': ['永'], 'tone': 'neutral', 'weight': 10},
    {'name': '开耀', 'themes': ['开'], 'tone': 'auspicious', 'weight': 12},
    {'name': '永淳', 'themes': ['永', '淳'], 'tone': 'neutral', 'weight': 10},
    {'name': '弘道', 'themes': ['弘'], 'tone': 'neutral', 'weight': 10},
    {'name': '嗣圣', 'themes': ['嗣', '圣'], 'tone': 'neutral', 'weight': 10},
    {'name': '文明', 'themes': ['文'], 'tone': 'neutral', 'weight': 10},
    {'name': '光宅', 'themes': ['光'], 'tone': 'neutral', 'weight': 10},
    {'name': '垂拱', 'themes': ['垂'], 'tone': 'neutral', 'weight': 10},
    {'name': '载初', 'themes': ['载'], 'tone': 'auspicious', 'weight': 12},
    {'name': '天授', 'themes': ['天'], 'tone': 'auspicious', 'weight': 12},
    {'name': '如意', 'themes': ['如'], 'tone': 'auspicious', 'weight': 12},
    {'name': '长寿', 'themes': ['长', '寿'], 'tone': 'auspicious', 'weight': 12},
    {'name': '延载', 'themes': ['延'], 'tone': 'neutral', 'weight': 10},
    {'name': '证圣', 'themes': ['证', '圣'], 'tone': 'auspicious', 'weight': 12},
    {'name': '天册万岁', 'themes': ['天'], 'tone': 'auspicious', 'weight': 4},
    {'name': '万岁登封', 'themes': ['万'], 'tone': 'auspicious', 'weight': 4},
    {'name': '万岁通天', 'themes': ['万', '天'], 'tone': 'auspicious', 'weight': 4},
    {'name': '神功', 'themes': ['神'], 'tone': 'auspicious', 'weight': 12},
    {'name': '圣历', 'themes': ['圣'], 'tone': 'auspicious', 'weight': 12},
    {'name': '久视', 'themes': ['久'], 'tone': 'auspicious', 'weight': 12},
    {'name': '大足', 'themes': ['大'], 'tone': 'auspicious', 'weight': 12},
    {'name': '长安', 'themes': ['长', '安'], 'tone': 'mitigate', 'weight': 11},
    {'name': '神龙', 'themes': ['神', '龙'], 'tone': 'auspicious', 'weight': 12},
    {'name': '景龙', 'themes': ['景', '龙'], 'tone': 'auspicious', 'weight': 12},
    {'name': '唐隆', 'themes': ['唐'], 'tone': 'neutral', 'weight': 10},
    {'name': '景云', 'themes': ['景'], 'tone': 'neutral', 'weight': 10},
    {'name': '太极', 'themes': ['太'], 'tone': 'neutral', 'weight': 10},
    {'name': '延和', 'themes': ['延', '和'], 'tone': 'mitigate', 'weight': 11},
    {'name': '先天', 'themes': ['先', '天'], 'tone': 'auspicious', 'weight': 12},
    {'name': '开元', 'themes': ['开', '元'], 'tone': 'auspicious', 'weight': 12},
    {'name': '天宝', 'themes': ['天', '宝'], 'tone': 'auspicious', 'weight': 12},
    {'name': '至德', 'themes': ['至'], 'tone': 'mitigate', 'weight': 11},
    {'name': '乾元', 'themes': ['乾', '元'], 'tone': 'auspicious', 'weight': 12},
    {'name': '宝应', 'themes': ['宝', '应'], 'tone': 'mitigate', 'weight': 11},
    {'name': '广德', 'themes': ['广'], 'tone': 'mitigate', 'weight': 11},
    {'name': '永泰', 'themes': ['永', '泰'], 'tone': 'mitigate', 'weight': 11},
    {'name': '大历', 'themes': ['大'], 'tone': 'auspicious', 'weight': 12},
    {'name': '建中', 'themes': ['建', '中'], 'tone': 'neutral', 'weight': 10},
    {'name': '兴元', 'themes': ['兴', '元'], 'tone': 'mitigate', 'weight': 11},
    {'name': '贞元', 'themes': ['贞', '元'], 'tone': 'auspicious', 'weight': 12},
    {'name': '永贞', 'themes': ['永'], 'tone': 'neutral', 'weight': 10},
    {'name': '长庆', 'themes': ['长', '庆'], 'tone': 'auspicious', 'weight': 12},
    {'name': '宝历', 'themes': ['宝'], 'tone': 'neutral', 'weight': 10},
    {'name': '大和', 'themes': ['大', '和'], 'tone': 'auspicious', 'weight': 12},
    {'name': '开成', 'themes': ['开', '成'], 'tone': 'auspicious', 'weight': 12},
    {'name': '会昌', 'themes': ['会'], 'tone': 'auspicious', 'weight': 12},
    {'name': '大中', 'themes': ['大', '中'], 'tone': 'auspicious', 'weight': 12},
    {'name': '咸通', 'themes': ['咸'], 'tone': 'neutral', 'weight': 10},
    {'name': '乾符', 'themes': ['乾'], 'tone': 'neutral', 'weight': 10},
    {'name': '广明', 'themes': ['广'], 'tone': 'neutral', 'weight': 10},
    {'name': '中和', 'themes': ['中', '和'], 'tone': 'mitigate', 'weight': 11},
    {'name': '光启', 'themes': ['光'], 'tone': 'neutral', 'weight': 10},
    {'name': '文德', 'themes': ['文'], 'tone': 'auspicious', 'weight': 12},
    {'name': '龙纪', 'themes': ['龙'], 'tone': 'auspicious', 'weight': 12},
    {'name': '大顺', 'themes': ['大', '顺'], 'tone': 'auspicious', 'weight': 12},
    {'name': '景福', 'themes': ['景', '福'], 'tone': 'auspicious', 'weight': 12},
    {'name': '乾宁', 'themes': ['乾', '宁'], 'tone': 'mitigate', 'weight': 11},
    {'name': '光化', 'themes': ['光'], 'tone': 'neutral', 'weight': 10},
    {'name': '天复', 'themes': ['天'], 'tone': 'mitigate', 'weight': 11},
    {'name': '天祐', 'themes': ['天'], 'tone': 'mitigate', 'weight': 11},
    {'name': '建隆', 'themes': ['建'], 'tone': 'auspicious', 'weight': 12},
    {'name': '乾德', 'themes': ['乾'], 'tone': 'auspicious', 'weight': 12},
    {'name': '开宝', 'themes': ['开', '宝'], 'tone': 'auspicious', 'weight': 12},
    {'name': '太平兴国', 'themes': ['太', '平', '兴'], 'tone': 'auspicious', 'weight': 4},
    {'name': '雍熙', 'themes': ['雍', '熙'], 'tone': 'neutral', 'weight': 10},
    {'name': '端拱', 'themes': ['端'], 'tone': 'neutral', 'weight': 10},
    {'name': '淳化', 'themes': ['淳'], 'tone': 'neutral', 'weight': 10},
    {'name': '至道', 'themes': ['至'], 'tone': 'neutral', 'weight': 10},
    {'name': '咸平', 'themes': ['咸', '平'], 'tone': 'auspicious', 'weight': 12},
    {'name': '景德', 'themes': ['景'], 'tone': 'auspicious', 'weight': 12},
    {'name': '大中祥符', 'themes': ['大', '中', '祥'], 'tone': 'auspicious', 'weight': 4},
    {'name': '天禧', 'themes': ['天'], 'tone': 'auspicious', 'weight': 12},
    {'name': '乾兴', 'themes': ['乾', '兴'], 'tone': 'neutral', 'weight': 10},
    {'name': '天圣', 'themes': ['天', '圣'], 'tone': 'auspicious', 'weight': 12},
    {'name': '明道', 'themes': ['明'], 'tone': 'auspicious', 'weight': 12},
    {'name': '景祐', 'themes': ['景'], 'tone': 'auspicious', 'weight': 12},
    {'name': '宝元', 'themes': ['宝', '元'], 'tone': 'auspicious', 'weight': 12},
    {'name': '康定', 'themes': ['康', '定'], 'tone': 'mitigate', 'weight': 11},
    {'name': '庆历', 'themes': ['庆'], 'tone': 'auspicious', 'weight': 12},
    {'name': '皇祐', 'themes': ['皇'], 'tone': 'auspicious', 'weight': 12},
    {'name': '至和', 'themes': ['至', '和'], 'tone': 'mitigate', 'weight': 11},
    {'name': '嘉祐', 'themes': ['嘉'], 'tone': 'auspicious', 'weight': 12},
    {'name': '治平', 'themes': ['治', '平'], 'tone': 'mitigate', 'weight': 11},
    {'name': '熙宁', 'themes': ['熙', '宁'], 'tone': 'auspicious', 'weight': 12},
    {'name': '元丰', 'themes': ['元'], 'tone': 'auspicious', 'weight': 12},
    {'name': '元祐', 'themes': ['元'], 'tone': 'auspicious', 'weight': 12},
    {'name': '绍圣', 'themes': ['绍', '圣'], 'tone': 'neutral', 'weight': 10},
    {'name': '元符', 'themes': ['元'], 'tone': 'auspicious', 'weight': 12},
    {'name': '建中靖国', 'themes': ['建', '中', '靖'], 'tone': 'auspicious', 'weight': 4},
    {'name': '崇宁', 'themes': ['崇', '宁'], 'tone': 'mitigate', 'weight': 11},
    {'name': '大观', 'themes': ['大'], 'tone': 'auspicious', 'weight': 12},
    {'name': '政和', 'themes': ['政', '和'], 'tone': 'mitigate', 'weight': 11},
    {'name': '重和', 'themes': ['重', '和'], 'tone': 'mitigate', 'weight': 11},
    {'name': '宣和', 'themes': ['宣', '和'], 'tone': 'mitigate', 'weight': 11},
    {'name': '靖康', 'themes': ['靖', '康'], 'tone': 'mitigate', 'weight': 11},
    {'name': '建炎', 'themes': ['建'], 'tone': 'mitigate', 'weight': 11},
    {'name': '绍兴', 'themes': ['绍', '兴'], 'tone': 'auspicious', 'weight': 12},
    {'name': '隆兴', 'themes': ['隆', '兴'], 'tone': 'neutral', 'weight': 10},
    {'name': '乾道', 'themes': ['乾'], 'tone': 'neutral', 'weight': 10},
    {'name': '淳熙', 'themes': ['淳', '熙'], 'tone': 'auspicious', 'weight': 12},
    {'name': '绍熙', 'themes': ['绍', '熙'], 'tone': 'neutral', 'weight': 10},
    {'name': '庆元', 'themes': ['庆', '元'], 'tone': 'auspicious', 'weight': 12},
    {'name': '嘉泰', 'themes': ['嘉', '泰'], 'tone': 'mitigate', 'weight': 11},
    {'name': '开禧', 'themes': ['开'], 'tone': 'auspicious', 'weight': 12},
    {'name': '嘉定', 'themes': ['嘉', '定'], 'tone': 'mitigate', 'weight': 11},
    {'name': '宝庆', 'themes': ['宝', '庆'], 'tone': 'neutral', 'weight': 10},
    {'name': '绍定', 'themes': ['绍', '定'], 'tone': 'mitigate', 'weight': 11},
    {'name': '端平', 'themes': ['端', '平'], 'tone': 'mitigate', 'weight': 11},
    {'name': '嘉熙', 'themes': ['嘉', '熙'], 'tone': 'neutral', 'weight': 10},
    {'name': '淳祐', 'themes': ['淳'], 'tone': 'neutral', 'weight': 10},
    {'name': '宝祐', 'themes': ['宝'], 'tone': 'neutral', 'weight': 10},
    {'name': '开庆', 'themes': ['开', '庆'], 'tone': 'auspicious', 'weight': 12},
    {'name': '景定', 'themes': ['景', '定'], 'tone': 'mitigate', 'weight': 11},
    {'name': '咸淳', 'themes': ['咸', '淳'], 'tone': 'neutral', 'weight': 10},
    {'name': '德祐', 'themes': ['德'], 'tone': 'mitigate', 'weight': 11},
    {'name': '景炎', 'themes': ['景'], 'tone': 'mitigate', 'weight': 11},
    {'name': '祥兴', 'themes': ['祥', '兴'], 'tone': 'mitigate', 'weight': 11},
    {'name': '中统', 'themes': ['中'], 'tone': 'neutral', 'weight': 10},
    {'name': '至元', 'themes': ['至', '元'], 'tone': 'auspicious', 'weight': 12},
    {'name': '元贞', 'themes': ['元'], 'tone': 'auspicious', 'weight': 12},
    {'name': '大德', 'themes': ['大'], 'tone': 'auspicious', 'weight': 12},
    {'name': '至大', 'themes': ['至', '大'], 'tone': 'auspicious', 'weight': 12},
    {'name': '皇庆', 'themes': ['皇', '庆'], 'tone': 'auspicious', 'weight': 12},
    {'name': '延祐', 'themes': ['延'], 'tone': 'auspicious', 'weight': 12},
    {'name': '至治', 'themes': ['至', '治'], 'tone': 'mitigate', 'weight': 11},
    {'name': '泰定', 'themes': ['泰', '定'], 'tone': 'mitigate', 'weight': 11},
    {'name': '致和', 'themes': ['致', '和'], 'tone': 'mitigate', 'weight': 11},
    {'name': '天历', 'themes': ['天'], 'tone': 'auspicious', 'weight': 12},
    {'name': '至顺', 'themes': ['至', '顺'], 'tone': 'mitigate', 'weight': 11},
    {'name': '元统', 'themes': ['元'], 'tone': 'auspicious', 'weight': 12},
    {'name': '至正', 'themes': ['至', '正'], 'tone': 'mitigate', 'weight': 11},
    {'name': '洪武', 'themes': ['洪', '武'], 'tone': 'auspicious', 'weight': 12},
    {'name': '建文', 'themes': ['建', '文'], 'tone': 'neutral', 'weight': 10},
    {'name': '永乐', 'themes': ['永'], 'tone': 'auspicious', 'weight': 12},
    {'name': '洪熙', 'themes': ['洪', '熙'], 'tone': 'neutral', 'weight': 10},
    {'name': '宣德', 'themes': ['宣'], 'tone': 'auspicious', 'weight': 12},
    {'name': '正统', 'themes': ['正'], 'tone': 'auspicious', 'weight': 12},
    {'name': '景泰', 'themes': ['景', '泰'], 'tone': 'mitigate', 'weight': 11},
    {'name': '天顺', 'themes': ['天', '顺'], 'tone': 'auspicious', 'weight': 12},
    {'name': '成化', 'themes': ['成'], 'tone': 'auspicious', 'weight': 12},
    {'name': '弘治', 'themes': ['弘', '治'], 'tone': 'auspicious', 'weight': 12},
    {'name': '正德', 'themes': ['正'], 'tone': 'auspicious', 'weight': 12},
    {'name': '嘉靖', 'themes': ['嘉', '靖'], 'tone': 'auspicious', 'weight': 12},
    {'name': '隆庆', 'themes': ['隆', '庆'], 'tone': 'neutral', 'weight': 10},
    {'name': '万历', 'themes': ['万'], 'tone': 'auspicious', 'weight': 12},
    {'name': '泰昌', 'themes': ['泰'], 'tone': 'auspicious', 'weight': 12},
    {'name': '天启', 'themes': ['天'], 'tone': 'auspicious', 'weight': 12},
    {'name': '崇祯', 'themes': ['崇', '祯'], 'tone': 'neutral', 'weight': 10},
    {'name': '顺治', 'themes': ['顺', '治'], 'tone': 'auspicious', 'weight': 12},
    {'name': '康熙', 'themes': ['康', '熙'], 'tone': 'auspicious', 'weight': 12},
    {'name': '雍正', 'themes': ['雍', '正'], 'tone': 'auspicious', 'weight': 12},
    {'name': '乾隆', 'themes': ['乾'], 'tone': 'auspicious', 'weight': 12},
    {'name': '嘉庆', 'themes': ['嘉', '庆'], 'tone': 'auspicious', 'weight': 12},
    {'name': '道光', 'themes': ['道', '光'], 'tone': 'auspicious', 'weight': 12},
    {'name': '咸丰', 'themes': ['咸'], 'tone': 'auspicious', 'weight': 12},
    {'name': '同治', 'themes': ['同', '治'], 'tone': 'auspicious', 'weight': 12},
    {'name': '光绪', 'themes': ['光'], 'tone': 'auspicious', 'weight': 12},
    {'name': '宣统', 'themes': ['宣'], 'tone': 'auspicious', 'weight': 12},
    {'name': '神瑞', 'themes': ['神', '瑞'], 'tone': 'auspicious', 'weight': 12},
    {'name': '泰常', 'themes': ['泰'], 'tone': 'mitigate', 'weight': 11},
    {'name': '始光', 'themes': ['始', '光'], 'tone': 'neutral', 'weight': 10},
    {'name': '太延', 'themes': ['太', '延'], 'tone': 'neutral', 'weight': 10},
    {'name': '正平', 'themes': ['正', '平'], 'tone': 'mitigate', 'weight': 11},
    {'name': '承平', 'themes': ['承', '平'], 'tone': 'mitigate', 'weight': 11},
    {'name': '兴安', 'themes': ['兴', '安'], 'tone': 'mitigate', 'weight': 11},
    {'name': '兴光', 'themes': ['兴', '光'], 'tone': 'mitigate', 'weight': 11},
    {'name': '天安', 'themes': ['天', '安'], 'tone': 'auspicious', 'weight': 12},
    {'name': '皇兴', 'themes': ['皇', '兴'], 'tone': 'neutral', 'weight': 10},
    {'name': '延兴', 'themes': ['延', '兴'], 'tone': 'neutral', 'weight': 10},
    {'name': '承明', 'themes': ['承'], 'tone': 'mitigate', 'weight': 11},
    {'name': '景明', 'themes': ['景'], 'tone': 'neutral', 'weight': 10},
    {'name': '延昌', 'themes': ['延'], 'tone': 'neutral', 'weight': 10},
    {'name': '熙平', 'themes': ['熙', '平'], 'tone': 'mitigate', 'weight': 11},
    {'name': '神龟', 'themes': ['神'], 'tone': 'neutral', 'weight': 10},
    {'name': '正光', 'themes': ['正', '光'], 'tone': 'neutral', 'weight': 10},
    {'name': '孝昌', 'themes': ['孝'], 'tone': 'neutral', 'weight': 10},
    {'name': '武泰', 'themes': ['武', '泰'], 'tone': 'mitigate', 'weight': 11},
    {'name': '建义', 'themes': ['建'], 'tone': 'neutral', 'weight': 10},
    {'name': '普泰', 'themes': ['普', '泰'], 'tone': 'mitigate', 'weight': 11},
    {'name': '中兴', 'themes': ['中', '兴'], 'tone': 'mitigate', 'weight': 11},
    {'name': '太昌', 'themes': ['太'], 'tone': 'neutral', 'weight': 10},
    {'name': '天赐', 'themes': ['天'], 'tone': 'auspicious', 'weight': 12},
    {'name': '天兴', 'themes': ['天', '兴'], 'tone': 'auspicious', 'weight': 12},
    {'name': '皇始', 'themes': ['皇'], 'tone': 'neutral', 'weight': 10},
    {'name': '登国', 'themes': ['登'], 'tone': 'neutral', 'weight': 10},
    {'name': '天保', 'themes': ['天'], 'tone': 'auspicious', 'weight': 12},
    {'name': '乾明', 'themes': ['乾'], 'tone': 'neutral', 'weight': 10},
    {'name': '皇建', 'themes': ['皇', '建'], 'tone': 'neutral', 'weight': 10},
    {'name': '河清', 'themes': ['河'], 'tone': 'mitigate', 'weight': 11},
    {'name': '天统', 'themes': ['天'], 'tone': 'auspicious', 'weight': 12},
    {'name': '武平', 'themes': ['武', '平'], 'tone': 'mitigate', 'weight': 11},
    {'name': '隆化', 'themes': ['隆'], 'tone': 'neutral', 'weight': 10},
    {'name': '承光', 'themes': ['承', '光'], 'tone': 'neutral', 'weight': 10},
    {'name': '天和', 'themes': ['天', '和'], 'tone': 'auspicious', 'weight': 12},
    {'name': '建德', 'themes': ['建'], 'tone': 'auspicious', 'weight': 12},
    {'name': '宣政', 'themes': ['宣'], 'tone': 'neutral', 'weight': 10},
    {'name': '大象', 'themes': ['大'], 'tone': 'auspicious', 'weight': 12},
    {'name': '大定', 'themes': ['大', '定'], 'tone': 'auspicious', 'weight': 12},
    {'name': '武义', 'themes': ['武'], 'tone': 'neutral', 'weight': 10},
    {'name': '黄武', 'themes': ['黄', '武'], 'tone': 'neutral', 'weight': 10},
    {'name': '嘉禾', 'themes': ['嘉'], 'tone': 'neutral', 'weight': 10},
    {'name': '赤乌', 'themes': ['赤'], 'tone': 'neutral', 'weight': 10},
    {'name': '神凤', 'themes': ['神', '凤'], 'tone': 'auspicious', 'weight': 12},
    {'name': '章武', 'themes': ['章', '武'], 'tone': 'neutral', 'weight': 10},
    {'name': '延熙', 'themes': ['延', '熙'], 'tone': 'neutral', 'weight': 10},
    {'name': '景耀', 'themes': ['景'], 'tone': 'neutral', 'weight': 10},
    {'name': '炎兴', 'themes': ['炎', '兴'], 'tone': 'neutral', 'weight': 10},
    {'name': '大兴', 'themes': ['大', '兴'], 'tone': 'auspicious', 'weight': 12},
    {'name': '景平', 'themes': ['景', '平'], 'tone': 'mitigate', 'weight': 11},
    {'name': '孝建', 'themes': ['孝', '建'], 'tone': 'neutral', 'weight': 10},
    {'name': '大明', 'themes': ['大'], 'tone': 'auspicious', 'weight': 12},
    {'name': '景和', 'themes': ['景', '和'], 'tone': 'mitigate', 'weight': 11},
    {'name': '泰豫', 'themes': ['泰'], 'tone': 'mitigate', 'weight': 11},
    {'name': '元徽', 'themes': ['元'], 'tone': 'auspicious', 'weight': 12},
    {'name': '升明', 'themes': ['升'], 'tone': 'neutral', 'weight': 10},
    {'name': '永明', 'themes': ['永'], 'tone': 'neutral', 'weight': 10},
    {'name': '隆昌', 'themes': ['隆'], 'tone': 'neutral', 'weight': 10},
    {'name': '天监', 'themes': ['天'], 'tone': 'auspicious', 'weight': 12},
    {'name': '普通', 'themes': ['普'], 'tone': 'neutral', 'weight': 10},
    {'name': '大通', 'themes': ['大'], 'tone': 'auspicious', 'weight': 12},
    {'name': '中大通', 'themes': ['中', '大'], 'tone': 'auspicious', 'weight': 6},
    {'name': '大同', 'themes': ['大', '同'], 'tone': 'auspicious', 'weight': 12},
    {'name': '中大同', 'themes': ['中', '大', '同'], 'tone': 'auspicious', 'weight': 6},
    {'name': '太清', 'themes': ['太'], 'tone': 'mitigate', 'weight': 11},
    {'name': '大宝', 'themes': ['大', '宝'], 'tone': 'auspicious', 'weight': 12},
    {'name': '天正', 'themes': ['天', '正'], 'tone': 'auspicious', 'weight': 12},
    {'name': '承圣', 'themes': ['承', '圣'], 'tone': 'neutral', 'weight': 10},
    {'name': '天成', 'themes': ['天', '成'], 'tone': 'auspicious', 'weight': 12},
    {'name': '绍泰', 'themes': ['绍', '泰'], 'tone': 'mitigate', 'weight': 11},
    {'name': '太平', 'themes': ['太', '平'], 'tone': 'auspicious', 'weight': 12},
    {'name': '天嘉', 'themes': ['天', '嘉'], 'tone': 'auspicious', 'weight': 12},
    {'name': '天康', 'themes': ['天', '康'], 'tone': 'auspicious', 'weight': 12},
    {'name': '光大', 'themes': ['光', '大'], 'tone': 'auspicious', 'weight': 12},
    {'name': '太建', 'themes': ['太', '建'], 'tone': 'neutral', 'weight': 10},
    {'name': '祯明', 'themes': ['祯'], 'tone': 'neutral', 'weight': 10},
    {'name': '永定', 'themes': ['永', '定'], 'tone': 'mitigate', 'weight': 11},
    {'name': '天玺', 'themes': ['天'], 'tone': 'auspicious', 'weight': 12},
    {'name': '天纪', 'themes': ['天'], 'tone': 'auspicious', 'weight': 12},
    {'name': '白雀', 'themes': ['白'], 'tone': 'neutral', 'weight': 10},
    {'name': '皇初', 'themes': ['皇'], 'tone': 'neutral', 'weight': 10},
    {'name': '弘始', 'themes': ['弘'], 'tone': 'neutral', 'weight': 10},
    {'name': '燕元', 'themes': ['燕', '元'], 'tone': 'auspicious', 'weight': 12},
    {'name': '太上', 'themes': ['太'], 'tone': 'neutral', 'weight': 10},
    {'name': '神鼎', 'themes': ['神'], 'tone': 'neutral', 'weight': 10},
    {'name': '龙飞', 'themes': ['龙'], 'tone': 'auspicious', 'weight': 12},
    {'name': '建衡', 'themes': ['建'], 'tone': 'neutral', 'weight': 10},
    {'name': '凤凰', 'themes': ['凤'], 'tone': 'auspicious', 'weight': 12},
    {'name': '汉兴', 'themes': ['汉', '兴'], 'tone': 'neutral', 'weight': 10},
    {'name': '嘉宁', 'themes': ['嘉', '宁'], 'tone': 'mitigate', 'weight': 11},
    {'name': '玉衡', 'themes': ['玉'], 'tone': 'neutral', 'weight': 10},
    {'name': '玉恒', 'themes': ['玉'], 'tone': 'neutral', 'weight': 10},
    {'name': '建世', 'themes': ['建'], 'tone': 'neutral', 'weight': 10},
    {'name': '龙兴', 'themes': ['龙', '兴'], 'tone': 'auspicious', 'weight': 12},
    {'name': '保定', 'themes': ['保', '定'], 'tone': 'mitigate', 'weight': 11},
    {'name': '同光', 'themes': ['同', '光'], 'tone': 'auspicious', 'weight': 12},
    {'name': '长兴', 'themes': ['长', '兴'], 'tone': 'neutral', 'weight': 10},
    {'name': '应顺', 'themes': ['应', '顺'], 'tone': 'mitigate', 'weight': 11},
    {'name': '清泰', 'themes': ['清', '泰'], 'tone': 'mitigate', 'weight': 11},
    {'name': '天福', 'themes': ['天', '福'], 'tone': 'auspicious', 'weight': 12},
    {'name': '开运', 'themes': ['开'], 'tone': 'auspicious', 'weight': 12},
    {'name': '天会', 'themes': ['天', '会'], 'tone': 'auspicious', 'weight': 12},
    {'name': '天眷', 'themes': ['天'], 'tone': 'auspicious', 'weight': 12},
    {'name': '皇统', 'themes': ['皇'], 'tone': 'neutral', 'weight': 10},
    {'name': '天德', 'themes': ['天'], 'tone': 'auspicious', 'weight': 12},
    {'name': '正隆', 'themes': ['正'], 'tone': 'neutral', 'weight': 10},
    {'name': '明昌', 'themes': ['明'], 'tone': 'neutral', 'weight': 10},
    {'name': '承安', 'themes': ['承', '安'], 'tone': 'mitigate', 'weight': 11},
    {'name': '泰和', 'themes': ['泰', '和'], 'tone': 'mitigate', 'weight': 11},
    {'name': '崇庆', 'themes': ['崇', '庆'], 'tone': 'neutral', 'weight': 10},
    {'name': '至宁', 'themes': ['至', '宁'], 'tone': 'mitigate', 'weight': 11},
    {'name': '贞祐', 'themes': ['贞'], 'tone': 'mitigate', 'weight': 11},
    {'name': '兴定', 'themes': ['兴', '定'], 'tone': 'mitigate', 'weight': 11},
    {'name': '正大', 'themes': ['正', '大'], 'tone': 'auspicious', 'weight': 12},
    {'name': '开兴', 'themes': ['开', '兴'], 'tone': 'auspicious', 'weight': 12},
    {'name': '收国', 'themes': ['收'], 'tone': 'neutral', 'weight': 10},
    {'name': '天辅', 'themes': ['天'], 'tone': 'auspicious', 'weight': 12},
    {'name': '统和', 'themes': ['统', '和'], 'tone': 'mitigate', 'weight': 11},
    {'name': '重熙', 'themes': ['重', '熙'], 'tone': 'neutral', 'weight': 10},
    {'name': '清宁', 'themes': ['清', '宁'], 'tone': 'mitigate', 'weight': 11},
    {'name': '咸雍', 'themes': ['咸'], 'tone': 'neutral', 'weight': 10},
    {'name': '寿昌', 'themes': ['寿'], 'tone': 'auspicious', 'weight': 12},
    {'name': '乾统', 'themes': ['乾'], 'tone': 'neutral', 'weight': 10},
    {'name': '天庆', 'themes': ['天', '庆'], 'tone': 'auspicious', 'weight': 12},
    {'name': '保大', 'themes': ['保', '大'], 'tone': 'mitigate', 'weight': 11},
    {'name': '显道', 'themes': ['显'], 'tone': 'neutral', 'weight': 10},
    {'name': '广运', 'themes': ['广'], 'tone': 'neutral', 'weight': 10},
    {'name': '大庆', 'themes': ['大', '庆'], 'tone': 'auspicious', 'weight': 12},
    {'name': '应天', 'themes': ['应', '天'], 'tone': 'mitigate', 'weight': 11},
    {'name': '乾定', 'themes': ['乾', '定'], 'tone': 'mitigate', 'weight': 11},
    {'name': '乾祐', 'themes': ['乾'], 'tone': 'neutral', 'weight': 10},
    {'name': '天命', 'themes': ['天'], 'tone': 'auspicious', 'weight': 12},
    {'name': '天聪', 'themes': ['天'], 'tone': 'auspicious', 'weight': 12},
    {'name': '崇德', 'themes': ['崇'], 'tone': 'auspicious', 'weight': 12},
    {'name': '太初元将', 'themes': ['太', '元'], 'tone': 'auspicious', 'weight': 4},
    {'name': '建武中元', 'themes': ['建', '武', '中', '元'], 'tone': 'auspicious', 'weight': 4},
    {'name': '天授礼法延祚', 'themes': ['天', '延'], 'tone': 'auspicious', 'weight': 4},
    {'name': '天祐垂圣', 'themes': ['天', '圣'], 'tone': 'auspicious', 'weight': 4},
    {'name': '天赐礼盛国庆', 'themes': ['天', '庆'], 'tone': 'auspicious', 'weight': 4},
    {'name': '大康', 'themes': ['大', '康'], 'tone': 'auspicious', 'weight': 12},
    {'name': '大安', 'themes': ['大', '安'], 'tone': 'auspicious', 'weight': 12},
    {'name': '光寿', 'themes': ['光', '寿'], 'tone': 'auspicious', 'weight': 12},
    {'name': '武成', 'themes': ['武', '成'], 'tone': 'neutral', 'weight': 10},
    {'name': '太平真君', 'themes': ['太', '平'], 'tone': 'mitigate', 'weight': 3},
]

NIANHAO_NAMES = [e["name"] for e in NIANHAO_ENTRIES]
NIANHAO_BY_NAME = {e["name"]: e for e in NIANHAO_ENTRIES}
